// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_WcVTdW9jpEG8EY8zihqeSeqXduNizQ',
    appId: '1:201589933797:web:73753afa5dae561d7c360c',
    messagingSenderId: '201589933797',
    projectId: 'todoapp-v2-22b03',
    authDomain: 'todoapp-v2-22b03.firebaseapp.com',
    storageBucket: 'todoapp-v2-22b03.appspot.com',
    measurementId: 'G-F88SMZG6W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb5OEgk4W2feoSQy43TCYauSwndQk0AK0',
    appId: '1:201589933797:android:6ff64e0670fff32d7c360c',
    messagingSenderId: '201589933797',
    projectId: 'todoapp-v2-22b03',
    storageBucket: 'todoapp-v2-22b03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6fIEIl7H3XPwS6RV80X-KYI7ETfMawc',
    appId: '1:201589933797:ios:2bf196900c8981c97c360c',
    messagingSenderId: '201589933797',
    projectId: 'todoapp-v2-22b03',
    storageBucket: 'todoapp-v2-22b03.appspot.com',
    iosClientId: '201589933797-0sdgnr0abjgmjv0o10foqrjnjmeuojm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM6fIEIl7H3XPwS6RV80X-KYI7ETfMawc',
    appId: '1:201589933797:ios:2bf196900c8981c97c360c',
    messagingSenderId: '201589933797',
    projectId: 'todoapp-v2-22b03',
    storageBucket: 'todoapp-v2-22b03.appspot.com',
    iosClientId: '201589933797-0sdgnr0abjgmjv0o10foqrjnjmeuojm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
